//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Alumnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNO
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public int EDAD { get; set; }
        public string SEXO { get; set; }
        public System.DateTime MOMENTO { get; set; }
        public Nullable<int> CIUDAD_ID { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
    }
}
